providers = ['node']
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1727136237'


[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'development'
NPM_CONFIG_PRODUCTION = 'true'


[phases.setup]
nixPkgs = ['nodejs_22', 'yarn-1_x']
nixOverlays = [
  'https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz',
]
nixpkgsArchive = 'e05605ec414618eab4a7a6aea8b38f6fbbcc8f08'


[phases.install]
dependsOn = ['setup']
cmds = [
  'npm install -g corepack@0.24.1 && corepack enable',
  'yarn install --check-cache',
]
cacheDirectories = ['/usr/local/share/.cache/yarn/v6']
paths = ['/app/node_modules/.bin']


[phases.build]
dependsOn = ['install']
cmds = ['medusa build']
cacheDirectories = ['node_modules/.cache']


[start]
cmd = 'medusa db:migrate && medusa start -p 9000'
